# All paths. Will have to changed when system is changed.
python_interpreter_path = "C:/Users/achar/AppData/Local/Programs/Python/Python312/python.exe"
packaging_script_path = "c:/Users/achar/Documents/College/IAS Hackathon Work/System_Files/package.py"
deployment_script_path = "c:/Users/achar/Documents/College/IAS Hackathon Work/System_Files/deploy.py"
configuration_script_path = "c:/Users/achar/Documents/College/IAS Hackathon Work/System_Files/inference_config.py"
models_folder_path = "c:/Users/achar/Documents/College/IAS Hackathon Work/Models"
packaged_models_folder_path = "c:/Users/achar/Documents/College/IAS Hackathon Work/System_Files/Packaged_Models"
deployed_models_folder_path = "c:/Users/achar/Documents/College/IAS Hackathon Work/System_Files/Deployed_Models"
dependency_files_folder_path = "c:/Users/achar/Documents/College/IAS Hackathon Work/Dependencies"
inference_config_files_folder_path = "c:/Users/achar/Documents/College/IAS Hackathon Work/Inference_Configs"
virtual_envs_folder_path = "c:/Users/achar/Documents/College/IAS Hackathon Work/System_Files/Virtual_Envs"
system_files_folder_path = "c:/Users/achar/Documents/College/IAS Hackathon Work/System_Files"